# Copyright 2021 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

version: "3"

#
# docker-compoes file to bring up the whole attestation engine
#
# Take note of lines that need to be edited, marked with #!!!
#
# Defacto ports for A10
#  8540 - U10
#  8542 - FC10
#  8560 - MQTT Channels
#  8561 - MQTT Channels (SSH)
#  8520 - A10REST
#  8530 - trust agents (on elements to be attested)     # Does not run here - not part of the server
#  8555 - mongo-express
#
# Configuration files
#  Edit the source of the a10.conf file
#  Should be the same for both u10 and a10rest
#

#
# The services needed to run the system
#

services:

#
# The core database
#  
   database:
     image: "mongo"
     container_name: mongo
     volumes:
      - attestationdata:/data/db
     networks:
      - attestationnetwork

#
# Useful tool for examining the database instead of using the mongo shell
#
# Mongoexpress listens normally on port 8081, we expose this on 8555
#
   databaseui:
     image: "mongo-express"
     ports: 
       - 8555:8081                          # !!!
     networks:
      - attestationnetwork
     environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_URL="mongodb://database:27017"
     restart: always
     depends_on: 
      - database
#
# Mosquitto for the MQTT channels
#
   messagebus:
     image: "eclipse-mosquitto"
     container_name: messagebus
     ports:
       - 8560:1883                          # !!!
       - 8561:9000                          # !!!
     networks:
      - attestationnetwork
     volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log

#
# U10 - the basic UI to the attestation database and engine
#    
   u10:
     image: "u10"
     container_name: u10     
     ports:
       - 8540:8540                           # !!!
     depends_on:
       - messagebus
     restart: always
     networks:
      - attestationnetwork
     volumes:
      - ./a10.conf:/etc/a10.conf      # !!!
      - attestationelementkeys:/var/attestation/keys
      
    # This will be needed by u10 and a10rest - anything that requires the a10 libraries
    # which uses ssh to communicate over the TPM2SENDSSH protocol
    # but docker and docke-compose make this super impossible to do in any sane manner
    

      #- $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
     #environment:
      #- SSH_AUTH_SOCK
#
# A10REST - the REST API to the attestation engine
#       
   a10rest:
    image: "a10rest"
    container_name: a10rest    
    ports:
      - 8520:8520                                # !!!
    depends_on:
      - messagebus  
    restart: always
    networks:
      - attestationnetwork
    volumes:
      - ./a10.conf:/etc/a10.conf      # !!!
      - attestationelementkeys:/var/attestation/keys


#
# FC10 - the REST API to the attestation engine
#       
   fc10:
    image: "fc10"
    container_name: fc10    
    ports:
      - 8542:8542                                # !!!
    depends_on:
      - a10rest  
    restart: always
    networks:
      - attestationnetwork


#
# This defines the permanent volume for storing the database
# so that it is permanent between starting and stopping the whole system
#

volumes:
  attestationdata: 
    external: true

  attestationelementkeys: 
    external: true

#
# Internal network
#

networks:
   attestationnetwork:
     driver: bridge
